import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    "intro",
    "crisis",
    {
      type: "category",
      label: "Paradigm 1: AI-Driven Development",
      items: [
        "ai-driven/what-is-aidriven",
        "ai-driven/workflow",
        "ai-driven/tools-2025",
        "ai-driven/case-studies",
        "ai-driven/risks",
      ],
    },
    {
      type: "category",
      label: "Paradigm 2: Spec-Driven Development",
      items: [
        "spec-driven/testing-is-dead",
        "spec-driven/executable-specs",
        "spec-driven/principles",
        "spec-driven/tools-2025",
        "spec-driven/million-dollar-bugs",
        "spec-driven/culture",
      ],
    },
  //   {
  //     type: "category",
  //     label: "The Superposition",
  //     items: [
  //       "superposition/why-1-plus-1-is-10",
  //       "superposition/integrated-workflow",
  //       "superposition/day-in-the-life",
  //       "superposition/reference-stacks",
  //       "superposition/metrics",
  //     ],
  //   },
  //   {
  //     type: "category",
  //     label: "Practical Adoption",
  //     items: [
  //       "adoption/first-ticket",
  //       "adoption/scaling",
  //       "adoption/pitfalls",
  //       "adoption/measuring",
  //     ],
  //   },
  //   "future",
  //   "conclusion",
  //   {
  //     type: "category",
  //     label: "Appendices",
  //     items: [
  //       "appendices/specks-templates",
  //       "appendices/prompt-library",
  //       "appendices/resources",
  //     ],
  //   },
  ],
};

export default sidebars;
